### ISSUE TITLE
New picker (v3)

### ISSUE THREAD

**Issue by mmahalwy** [ZeroCho/react-filepicker#144]

**Comment by ZeroCho** [comment]
@mmahalwy what do you mean by new picker? filepicker-js@3 came out?

**Comment by mmahalwy** [comment]
Thanks! :)

**Comment by ZeroCho** [comment]
@mmahalwy I published it as a new package [react-filestack](https://npmjs.com/package/react-filestack)) because it changed too much. It's not backward compatible. It's in beta now... if you find any bug, please tell me.

**Comment by mmahalwy** [comment]
+1. Thanks
