### ISSUE TITLE
Filepicker is being blocked on iOS mobile browsers.

### ISSUE THREAD

**Issue by vvillait88** [ZeroCho/react-filepicker#37]
I tested on Safari and Chrome for iOS on both your implementation and our implementation and the new window is being blocked from being opened

**Comment by ZeroCho** [comment]
Thank you for notifying me this problem. I'll figure out what blocks filepicker to be opened in IOS.

By the way, what do you mean by "our implementation"?

**Comment by vvillait88** [comment]
No problem, our implementation was just referring to our dev environment.

Thanks for jumping on this quickly!

**Comment by vvillait88** [comment]
@ZeroCho Any update on this?

**Comment by ZeroCho** [comment]
@vvillait88 sorry for the late reply... and i can't find why it's not possible only on iOS.
Have you tried pure filepicker.js? If you can't make it with pure filepicker.js, then it's not my package's problem but filepicker itself.

**Comment by ZeroCho** [comment]
I'll close this temporarily. If you have continuing problem, please reopen this.
