### ISSUE TITLE
component options not responding to state changes

### ISSUE THREAD

**Issue by cshanejennings** [ZeroCho/react-filepicker#71]
I have a controlled input for setting the height of a component to allow me to set the correct cropRatio that I need for the final image.  The width of the image is set to 600 and the height is originally set to 200 giving an aspect ratio of 3.  The options I'm passing into the control trace out to the console as follows:

```
{
	"imageQuality": 100,
	"buttonText": "Upload Banner",
	"backgroundUpload": false,
	"mimetypes": ["image/*"],
	"imageDim": [600, 200],
	"cropForce": true,
	"cropRatio": 3
}
```

When I update the text field for the image height to 100, I can see the imageDim and and cropRatio reflected in the console as:
```
{
	"imageQuality": 100,
	"buttonText": "Upload Banner",
	"backgroundUpload": false,
	"mimetypes": ["image/*"],
	"imageDim": [600, 100],
	"cropForce": true,
	"cropRatio": 6
}
```

However... when I click the Button labeled "Upload Banner", the cropRatio matches the default, and not the updated options.  Is there an additional step, am I doing something wrong or is this a bug?

**Comment by cshanejennings** [comment]
I took a look at this and it looks like the parameters are only set in componentDidMount
https://github.com/ZeroCho/react-filepicker/blob/master/src/ReactFilepicker.jsx

I couldn't get the build to come out because of a missing preset "babel-preset-stage-1" file, but I forked and have the changes I wanted to test here:
https://github.com/cshanejennings/react-filepicker/blob/master/src/ReactFilepicker.jsx

This is a very crude attempt, but it might work?  Any thoughts?

**Comment by cshanejennings** [comment]
I took a look at this and it looks like the parameters are only set in componentDidMount
https://github.com/ZeroCho/react-filepicker/blob/master/src/ReactFilepicker.jsx

I forked, but I couldn't get the build to come out because of a missing preset "babel-preset-stage-1" file.  What I was attempting to do was to put componentDidMount into a method called "update(props = this.props)" and then call it on componentDidMount and componentWillReceiveProps and see if that works.  Crude, but it might work?  Any thoughts?

**Comment by ZeroCho** [comment]
@cshanejennings 
When I first published this package. I didn't plan to support dynamic props change. **filepicker.js** doesn't support module system, so it's very tricky to use it in react.js.

Any PR is welcomed.

By the way, what do you mean by **missing preset 'babel-preset-stage-1'**?

**Comment by cshanejennings** [comment]
Ah, ok got it.  Is there any way to change the configuration via the filepicker object or does the entire object need to be recreated?

Not really sure about the error, that's just what I'm getting from the console after `npm run build`

**Comment by ZeroCho** [comment]
I think it should be recreated. Filepicker is initiated only once and cannot be changed afterward. I guess you should destory original one and recreate new one.

**Comment by cshanejennings** [comment]
This seems to do the trick:

```
    getFilePicker() {
        const options = this.getOptions();
        const {optionKey} = this.props;
        return (
            <div key={ optionKey }>
                <ReactFilepicker
                    defaultWidget
                    buttonClass="btn btn-lg icon-btn upload-banner"
                    apikey={ FILESTACK_API_KEY }
                    options={ options }
                    onSuccess={ this.filePickerComplete }
                />
            </div>
        );
    }
```
I pass a number in every time the options are updated.  The key property destroys the previous instance and creates a new one.  I tried putting the key on ReactFilepicker, but I just ended up with multiple copies of the control without a good way to get rid of them.

**Comment by ZeroCho** [comment]
@cshanejennings Thank you!
