### ISSUE TITLE
Error when attempting to load videos

### ISSUE THREAD

**Issue by JperF** [ZeroCho/react-filepicker#93]
I am trying to create a file picker that is limited to just video file formats but I am receiving an error when the picker is loaded. 

```
[uuid=A097EC5393404C5E] Error: the service convert couldn't be found or does not support the given mimetype(s): [u'video/*']
```

I am using it as follows:

### Usage
````javascript
<ReactFilepicker apikey={API_KEY} defaultWidget={false} options={options} onSuccess={this.uploadSuccess.bind(this)} />
````

### Options
````javascript
{
        buttonText  : 'Add Video Resume',
        mimetype    : 'video/*',
        buttonClass : 'buttonClass',
        cropRatio   : 1,
        conversions : ['crop', 'rotate', 'filter'],
        services    : ['CONVERT', 'COMPUTER', 'DROPBOX', 'FACEBOOK', 'INSTAGRAM', 'URL', 'WEBCAM', 'GOOGLE_DRIVE', 'GMAIL', 'BOX', 'CLOUDDRIVE', 'GITHUB', 'FLICKR', 'EVERNOTE', 'SKYDRIVE', 'PICASA', 'CLOUDAPP', 'IMGUR']
      }
````

**Comment by ZeroCho** [comment]
Thank you for reporting. I'll reproduce it and try to figure out today.

**Comment by ZeroCho** [comment]
@JperF Try this temporarily [http://stackoverflow.com/questions/14330308/filepicker-io-video-mimetype-does-not-work-in-chrome](link). I'm not sure this is fixed yet

**Comment by ZeroCho** [comment]
@JperF 
I find out why error happens. Some services doesn't support video uploads, such as convert and facebook.
Just remove services property from your option.
Documentation says that 
> Be sure that the services you select are compatible with the mimetype(s) or extension(s) specified.

**Comment by JperF** [comment]
@ZeroCho 
Thanks for the information! Sorry for not seeing that in the docs.
